---
title: "Tabset Column"
output: flexdashboard::flex_dashboard

---
```{r, eval=TRUE, echo=FALSE, message=FALSE }
load("contents_of_excelfile.RData")
library(tidyverse)
```

# Courses {data-icon="ion-apps-outline"}
    
## Column   {.tabset .tabset-fade}
### Table
    
```{r}
DT::datatable(courses)
```
   

   
### Graph

```{r}

```   
 
 
# Participants  {data-icon="fa-list"}
### Chart 3
    
```{r}
```


# Participants reached  {data-icon="fa-solid fa-arrows-turn-to-dots"}

```{r}
totalworkforce <- participants %>% summarise(sum(N, na.rm = TRUE)) %>% pull() 
totaleducated <- courses %>% summarise(sum(number, na.rm = TRUE)) %>% pull()
cubelength <- floor(sqrt(totalworkforce))

df <- tibble(
  yaxis = rep(seq(1:cubelength), each = cubelength),
  xaxis = rep(seq(1:cubelength), times = cubelength),
  educated = c(rep("educated", totaleducated), rep("noteducated", cubelength^2-totaleducated))
)

g <- for(i in courses$name) {
  test <- rep(i, times = 5)
  test
}

v1 <- c("a", "b", "c")
v2 <- c(0, 1, 2)
v1 *v2
rep(courses$name,  courses$number)

map(.x = courses, .f = mean(number))

ggplot(df, aes(x = xaxis, y = yaxis, colour = educated)) +
  geom_point() +
  theme_void()

```

